server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sh7513244


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: true